### ISSUE TITLE
Bug: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by iporat08** [RanHadar/MyPingPongTable#16]
Hey, 
When i'm trying to enter my name at the very first pop-up presented to the user, the app crashes when I press the "LET'S PONG !" button. 
The error I get in the Logcat is the following:
![Annotation 2020-06-25 175939](https://user-images.githubusercontent.com/51414337/85744688-c1141c80-b70d-11ea-883b-4043c45d709a.png)

Good luck!
Ido

**Comment by RanHadar** [comment]
Known issue, thanks fixed that :)
