### ISSUE TITLE
If user tries to press the "LET'S PONG" button on the opening dialog without entering a name the app crashes.

### ISSUE THREAD

**Issue by carmelLevy** [RanHadar/MyPingPongTable#17]
Hi,
I tried to see what happens when you press the "LET'S PONG" button on the opening dialog without entering a name and the app crashed. 
It seems that the function "confirmName(View) " is missing. 

I'm adding a screenshot of the error I got : 

![image](https://user-images.githubusercontent.com/50371133/85783580-1fea8d80-b730-11ea-970c-ede2d9784b20.png)

**Comment by RanHadar** [comment]
Known issue, thanks fixed that :)
