### ISSUE TITLE
Failing to compile and run the app

### ISSUE THREAD

**Issue by asaf-kali** [RanHadar/MyPingPongTable#19]
I'v cloned the project and tried to run it (Im on commit 6ec003f4883fa78618087df91eb130a966ba7cf2).
When I build the project, I get a compilation error:
![image](https://user-images.githubusercontent.com/28392088/85901574-cb681080-b80a-11ea-9f89-4e769f2f6b5c.png)

These are the relevant lines:
![image](https://user-images.githubusercontent.com/28392088/85901618-e044a400-b80a-11ea-986a-70ac616d064e.png)

What could be the issue?
Thans

**Comment by RanHadar** [comment]
Thanks! Fixed that, the app should work well now
