### ISSUE TITLE
BUG - when opening the calender from main screen it let's you pick dates from the past

### ISSUE THREAD

**Issue by carmelLevy** [RanHadar/MyPingPongTable#21]
Hi,
When opening the calender from main screen it let's you pick dates from the past.
I suggest you to pop a dialog or a toast explaining the user he has to choose a valid date and disallow him from picking an illegal one.
![WhatsApp Image 2020-06-27 at 14 34 53](https://user-images.githubusercontent.com/50371133/85921225-68669000-b883-11ea-9fa8-50a7c602671d.jpeg)

**Comment by RanHadar** [comment]
Fixed by Mor, thanks!
