### ISSUE TITLE
Bug: display flips when the phone has a language which is right-to-left

### ISSUE THREAD

**Issue by mormoshe** [RanHadar/MyPingPongTable#26]
My phone's language is Hebrew, so the app display appears like this:
![WhatsApp Image 2020-06-27 at 16 01 07](https://user-images.githubusercontent.com/40175415/85922944-889c4c00-b88f-11ea-93a6-45261bc6fa2b.jpeg)

**Comment by RanHadar** [comment]
Thanks for the fix!
