### ISSUE TITLE
BUG- when you join at least 2 games and try adding one of them to the calender, when moving with the arrows the app crashes

### ISSUE THREAD

**Issue by carmelLevy** [RanHadar/MyPingPongTable#33]
Hi, 
I tried to register to 2 games and then add them to my calender. In the "ADD TO CALENDER" dialog the I moved back and forth with the arrows (which allows the user to pick the specific game he want's to add to his calender) and the app crashed.
Here is a screenshot of ther error I got : 

![WhatsApp Image 2020-06-29 at 12 40 10](https://user-images.githubusercontent.com/50371133/85994871-48130e80-ba06-11ea-8431-057e2ec44b6a.jpeg)

I think maybe it happened becuse of out of bound access to the user reserved games array.

**Comment by RanHadar** [comment]
Done :)
