### ISSUE TITLE
BUG - A user can book himself into a game in the past. I tried bookinga game which supposed to be 2 hrs ago, and the app let me 

### ISSUE THREAD

**Issue by carmelLevy** [RanHadar/MyPingPongTable#40]
Hi! 
I tried bookinga game which supposed to be 2 hrs ago, and the app let me.
I suggest you to maybe disable that option for the user, in order to avoid unwanted behaviour. 
Maybe when a user tries to do so , you can pop some nice UI explaining that he can't book this hour.  

![WhatsApp Image 2020-07-02 at 21 31 47](https://user-images.githubusercontent.com/50371133/86396911-84b36400-bcab-11ea-9551-e0ab5e0666f5.jpeg)

**Comment by RanHadar** [comment]
Fixed. thanks
