### ISSUE TITLE
bug - problem with font scaling

### ISSUE THREAD

**Issue by ShaharBirzon** [RanHadar/MyPingPongTable#42]
As you probably know, when using `sp` units for font size, the app texts will re-scale according to the font size the user chose on the phone settings. In your app, the scaling of the texts interrupts some views in the app (some texts are cut or wrapped) as you can see here:
![pingpong](https://user-images.githubusercontent.com/39333878/86529648-e8f84280-beba-11ea-8fbf-a2a3e1d98dff.jpeg)
So technically, you have two options:
1. change the font size units to `dp` .
2. add a configuration override method that prevents the scaling for big fonts.

I think the second option is more straight forward and saves lots of work. 
Therefore, I implemented this for you in pr #43 

hope you like that!

**Comment by RanHadar** [comment]
Thanks for the fix!
